// <auto-generated />
using System;
using KClock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KClock.Data.Migrations
{
    [DbContext(typeof(ClockDbContext))]
    [Migration("20260922230701_IsolationViewsAndGrants")]
    partial class IsolationViewsAndGrants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KClock.Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("KClock.Data.Entities.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hardware_id");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int?>("PolicyFlushS")
                        .HasColumnType("integer")
                        .HasColumnName("policy_flush_s");

                    b.Property<int?>("PolicyMaxBatch")
                        .HasColumnType("integer")
                        .HasColumnName("policy_max_batch");

                    b.Property<int?>("PolicySampleS")
                        .HasColumnType("integer")
                        .HasColumnName("policy_sample_s");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile");

                    b.HasKey("Id")
                        .HasName("pk_device");

                    b.HasIndex("HardwareId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_hardware_id");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("KClock.Data.Entities.DeviceAccess", b =>
                {
                    b.Property<long>("BindingId")
                        .HasColumnType("bigint")
                        .HasColumnName("binding_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("BindingId", "AccountId")
                        .HasName("pk_device_access");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_device_access_account_id");

                    b.ToTable("device_access", (string)null);
                });

            modelBuilder.Entity("KClock.Data.Entities.DeviceBinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("BoundAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bound_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset?>("UnboundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unbound_at");

                    b.Property<string>("UnboundReason")
                        .HasColumnType("text")
                        .HasColumnName("unbound_reason");

                    b.HasKey("Id")
                        .HasName("pk_device_binding");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_device_binding_account_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_binding_device_id");

                    b.ToTable("device_binding", (string)null);
                });

            modelBuilder.Entity("KClock.Data.Entities.DeviceCredential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("BindingId")
                        .HasColumnType("bigint")
                        .HasColumnName("binding_id");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_device_credential");

                    b.HasIndex("BindingId")
                        .HasDatabaseName("ix_device_credential_binding_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_credential_device_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_device_credential_token_hash");

                    b.ToTable("device_credential", (string)null);
                });

            modelBuilder.Entity("KClock.Data.Entities.DeviceState", b =>
                {
                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<string>("EspVersion")
                        .HasColumnType("text")
                        .HasColumnName("esp_version");

                    b.Property<DateTimeOffset?>("LastIngestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ingest_at");

                    b.Property<long?>("LastSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("last_seq");

                    b.Property<string>("NanoVersion")
                        .HasColumnType("text")
                        .HasColumnName("nano_version");

                    b.HasKey("DeviceId")
                        .HasName("pk_device_state");

                    b.ToTable("device_state", (string)null);
                });

            modelBuilder.Entity("KClock.Data.Entities.EnrollmentCode", b =>
                {
                    b.Property<byte[]>("CodeHash")
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<long?>("ConsumedDeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("consumed_device_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("CodeHash")
                        .HasName("pk_enrollment_code");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_enrollment_code_account_id");

                    b.ToTable("enrollment_code", (string)null);
                });

            modelBuilder.Entity("KClock.Data.Entities.ExternalLogin", b =>
                {
                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.HasKey("Provider", "Subject")
                        .HasName("pk_external_login");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_external_login_account_id");

                    b.ToTable("external_login", (string)null);
                });

            modelBuilder.Entity("KClock.Data.Entities.Telemetry", b =>
                {
                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("Ts")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.Property<long>("BindingId")
                        .HasColumnType("bigint")
                        .HasColumnName("binding_id");

                    b.Property<int?>("EspFreeHeapB")
                        .HasColumnType("integer")
                        .HasColumnName("esp_free_heap_b");

                    b.Property<int?>("EspUptimeS")
                        .HasColumnType("integer")
                        .HasColumnName("esp_uptime_s");

                    b.Property<short?>("HumidityPct")
                        .HasColumnType("smallint")
                        .HasColumnName("humidity_pct");

                    b.Property<int?>("LinkDropped")
                        .HasColumnType("integer")
                        .HasColumnName("link_dropped");

                    b.Property<int?>("LinkGood")
                        .HasColumnType("integer")
                        .HasColumnName("link_good");

                    b.Property<int?>("LinkRejected")
                        .HasColumnType("integer")
                        .HasColumnName("link_rejected");

                    b.Property<short?>("PressureMmhg")
                        .HasColumnType("smallint")
                        .HasColumnName("pressure_mmhg");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short?>("TemperatureDc")
                        .HasColumnType("smallint")
                        .HasColumnName("temperature_dc");

                    b.Property<short?>("WifiRssiDbm")
                        .HasColumnType("smallint")
                        .HasColumnName("wifi_rssi_dbm");

                    b.HasKey("DeviceId", "Ts")
                        .HasName("pk_telemetry");

                    b.ToTable("telemetry", null, t =>
                        {
                            t.HasCheckConstraint("ck_telemetry_humidity_pct", "humidity_pct BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("KClock.Data.Entities.DeviceAccess", b =>
                {
                    b.HasOne("KClock.Data.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_access_account_account_id");

                    b.HasOne("KClock.Data.Entities.DeviceBinding", "Binding")
                        .WithMany("Access")
                        .HasForeignKey("BindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_access_device_bindings_binding_id");

                    b.Navigation("Account");

                    b.Navigation("Binding");
                });

            modelBuilder.Entity("KClock.Data.Entities.DeviceBinding", b =>
                {
                    b.HasOne("KClock.Data.Entities.Account", "Account")
                        .WithMany("DeviceBindings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_binding_account_account_id");

                    b.HasOne("KClock.Data.Entities.Device", "Device")
                        .WithMany("Bindings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_binding_devices_device_id");

                    b.Navigation("Account");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("KClock.Data.Entities.DeviceCredential", b =>
                {
                    b.HasOne("KClock.Data.Entities.DeviceBinding", "Binding")
                        .WithMany("Credentials")
                        .HasForeignKey("BindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_credential_device_binding_binding_id");

                    b.HasOne("KClock.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_credential_device_device_id");

                    b.Navigation("Binding");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("KClock.Data.Entities.DeviceState", b =>
                {
                    b.HasOne("KClock.Data.Entities.Device", null)
                        .WithOne()
                        .HasForeignKey("KClock.Data.Entities.DeviceState", "DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_state_device_device_id");
                });

            modelBuilder.Entity("KClock.Data.Entities.EnrollmentCode", b =>
                {
                    b.HasOne("KClock.Data.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_code_account_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("KClock.Data.Entities.ExternalLogin", b =>
                {
                    b.HasOne("KClock.Data.Entities.Account", "Account")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_login_account_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("KClock.Data.Entities.Account", b =>
                {
                    b.Navigation("DeviceBindings");

                    b.Navigation("ExternalLogins");
                });

            modelBuilder.Entity("KClock.Data.Entities.Device", b =>
                {
                    b.Navigation("Bindings");
                });

            modelBuilder.Entity("KClock.Data.Entities.DeviceBinding", b =>
                {
                    b.Navigation("Access");

                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
